# Fetching Data through TMDB API

### Importing necessary libraries

In [1]:
import pandas as pd
import requests as re

## Fetching data through API

In [2]:
# TMDB API base URL
base_url = 'https://api.themoviedb.org/3/discover/movie'
api_key = '5b79eab8702a08b73d650a25fb17cfd2'

# Parameters that are constant for each request
params = {
    'include_adult': 'false',
    'include_video': 'false',
    'language': 'en-US',
    'sort_by': 'vote_average.desc',
    'without_genres': '99,10755',
    'vote_count.gte': '200',
    'api_key': api_key,
    'page': 1  # start from page 1
}

# First request to get total pages
response = re.get(base_url, params=params)

if response.status_code != 200:
    raise Exception(f"Failed to fetch data: {response.status_code}")

data = response.json()
total_pages = data['total_pages']
print(f"Total pages available: {total_pages}")

# Initialize list with first page results
all_movies = data['results']

# Loop through remaining pages
for page in range(2, total_pages + 1):
    print(f"Fetching page {page}...")
    params['page'] = page
    response = re.get(base_url, params=params)
    
    if response.status_code == 200:
        page_data = response.json()
        all_movies.extend(page_data['results'])
    else:
        print(f"Failed to fetch page {page}, status code: {response.status_code}")

# Convert to DataFrame
df = pd.DataFrame(all_movies)

Total pages available: 659
Fetching page 2...
Fetching page 3...
Fetching page 4...
Fetching page 5...
Fetching page 6...
Fetching page 7...
Fetching page 8...
Fetching page 9...
Fetching page 10...
Fetching page 11...
Fetching page 12...
Fetching page 13...
Fetching page 14...
Fetching page 15...
Fetching page 16...
Fetching page 17...
Fetching page 18...
Fetching page 19...
Fetching page 20...
Fetching page 21...
Fetching page 22...
Fetching page 23...
Fetching page 24...
Fetching page 25...
Fetching page 26...
Fetching page 27...
Fetching page 28...
Fetching page 29...
Fetching page 30...
Fetching page 31...
Fetching page 32...
Fetching page 33...
Fetching page 34...
Fetching page 35...
Fetching page 36...
Fetching page 37...
Fetching page 38...
Fetching page 39...
Fetching page 40...
Fetching page 41...
Fetching page 42...
Fetching page 43...
Fetching page 44...
Fetching page 45...
Fetching page 46...
Fetching page 47...
Fetching page 48...
Fetching page 49...
Fetching page 50...
Fetching page 51...
Fetching page 52...
Fetching page 53...
Fetching page 54...
Fetching page 55...
Fetching page 56...
Fetching page 57...
Fetching page 58...
Fetching page 59...
Fetching page 60...
Fetching page 61...
Fetching page 62...
Fetching page 63...
Fetching page 64...
Fetching page 65...
Fetching page 66...
Fetching page 67...
Fetching page 68...
Fetching page 69...
Fetching page 70...
Fetching page 71...
Fetching page 72...
Fetching page 73...
Fetching page 74...
Fetching page 75...
Fetching page 76...
Fetching page 77...
Fetching page 78...
Fetching page 79...
Fetching page 80...
Fetching page 81...
Fetching page 82...
Fetching page 83...
Fetching page 84...
Fetching page 85...
Fetching page 86...
Fetching page 87...
Fetching page 88...
Fetching page 89...
Fetching page 90...
Fetching page 91...
Fetching page 92...
Fetching page 93...
Fetching page 94...
Fetching page 95...
Fetching page 96...
Fetching page 97...
Fetching page 98...
Fetching page 99...
Fetching page 100...
Fetching page 101...
Fetching page 102...
Fetching page 103...
Fetching page 104...
Fetching page 105...
Fetching page 106...
Fetching page 107...
Fetching page 108...
Fetching page 109...
Fetching page 110...
Fetching page 111...
Fetching page 112...
Fetching page 113...
Fetching page 114...
Fetching page 115...
Fetching page 116...
Fetching page 117...
Fetching page 118...
Fetching page 119...
Fetching page 120...
Fetching page 121...
Fetching page 122...
Fetching page 123...
Fetching page 124...
Fetching page 125...
Fetching page 126...
Fetching page 127...
Fetching page 128...
Fetching page 129...
Fetching page 130...
Fetching page 131...
Fetching page 132...
Fetching page 133...
Fetching page 134...
Fetching page 135...
Fetching page 136...
Fetching page 137...
Fetching page 138...
Fetching page 139...
Fetching page 140...
Fetching page 141...
Fetching page 142...
Fetching page 143...
Fetching page 144...
Fetching page 145...
Fetching page 146...
Fetching page 147...
Fetching page 148...
Fetching page 149...
Fetching page 150...
Fetching page 151...
Fetching page 152...
Fetching page 153...
Fetching page 154...
Fetching page 155...
Fetching page 156...
Fetching page 157...
Fetching page 158...
Fetching page 159...
Fetching page 160...
Fetching page 161...
Fetching page 162...
Fetching page 163...
Fetching page 164...
Fetching page 165...
Fetching page 166...
Fetching page 167...
Fetching page 168...
Fetching page 169...
Fetching page 170...
Fetching page 171...
Fetching page 172...
Fetching page 173...
Fetching page 174...
Fetching page 175...
Fetching page 176...
Fetching page 177...
Fetching page 178...
Fetching page 179...
Fetching page 180...
Fetching page 181...
Fetching page 182...
Fetching page 183...
Fetching page 184...
Fetching page 185...
Fetching page 186...
Fetching page 187...
Fetching page 188...
Fetching page 189...
Fetching page 190...
Fetching page 191...
Fetching page 192...
Fetching page 193...
Fetching page 194...
Fetching page 195...
Fetching page 196...
Fetching page 197...
Fetching page 198...
Fetching page 199...
Fetching page 200...
Fetching page 201...
Fetching page 202...
Fetching page 203...
Fetching page 204...
Fetching page 205...
Fetching page 206...
Fetching page 207...
Fetching page 208...
Fetching page 209...
Fetching page 210...
Fetching page 211...
Fetching page 212...
Fetching page 213...
Fetching page 214...
Fetching page 215...
Fetching page 216...
Fetching page 217...
Fetching page 218...
Fetching page 219...
Fetching page 220...
Fetching page 221...
Fetching page 222...
Fetching page 223...
Fetching page 224...
Fetching page 225...
Fetching page 226...
Fetching page 227...
Fetching page 228...
Fetching page 229...
Fetching page 230...
Fetching page 231...
Fetching page 232...
Fetching page 233...
Fetching page 234...
Fetching page 235...
Fetching page 236...
Fetching page 237...
Fetching page 238...
Fetching page 239...
Fetching page 240...
Fetching page 241...
Fetching page 242...
Fetching page 243...
Fetching page 244...
Fetching page 245...
Fetching page 246...
Fetching page 247...
Fetching page 248...
Fetching page 249...
Fetching page 250...
Fetching page 251...
Fetching page 252...
Fetching page 253...
Fetching page 254...
Fetching page 255...
Fetching page 256...
Fetching page 257...
Fetching page 258...
Fetching page 259...
Fetching page 260...
Fetching page 261...
Fetching page 262...
Fetching page 263...
Fetching page 264...
Fetching page 265...
Fetching page 266...
Fetching page 267...
Fetching page 268...
Fetching page 269...
Fetching page 270...
Fetching page 271...
Fetching page 272...
Fetching page 273...
Fetching page 274...
Fetching page 275...
Fetching page 276...
Fetching page 277...
Fetching page 278...
Fetching page 279...
Fetching page 280...
Fetching page 281...
Fetching page 282...
Fetching page 283...
Fetching page 284...
Fetching page 285...
Fetching page 286...
Fetching page 287...
Fetching page 288...
Fetching page 289...
Fetching page 290...
Fetching page 291...
Fetching page 292...
Fetching page 293...
Fetching page 294...
Fetching page 295...
Fetching page 296...
Fetching page 297...
Fetching page 298...
Fetching page 299...
Fetching page 300...
Fetching page 301...
Fetching page 302...
Fetching page 303...
Fetching page 304...
Fetching page 305...
Fetching page 306...
Fetching page 307...
Fetching page 308...
Fetching page 309...
Fetching page 310...
Fetching page 311...
Fetching page 312...
Fetching page 313...
Fetching page 314...
Fetching page 315...
Fetching page 316...
Fetching page 317...
Fetching page 318...
Fetching page 319...
Fetching page 320...
Fetching page 321...
Fetching page 322...
Fetching page 323...
Fetching page 324...
Fetching page 325...
Fetching page 326...
Fetching page 327...
Fetching page 328...
Fetching page 329...
Fetching page 330...
Fetching page 331...
Fetching page 332...
Fetching page 333...
Fetching page 334...
Fetching page 335...
Fetching page 336...
Fetching page 337...
Fetching page 338...
Fetching page 339...
Fetching page 340...
Fetching page 341...
Fetching page 342...
Fetching page 343...
Fetching page 344...
Fetching page 345...
Fetching page 346...
Fetching page 347...
Fetching page 348...
Fetching page 349...
Fetching page 350...
Fetching page 351...
Fetching page 352...
Fetching page 353...
Fetching page 354...
Fetching page 355...
Fetching page 356...
Fetching page 357...
Fetching page 358...
Fetching page 359...
Fetching page 360...
Fetching page 361...
Fetching page 362...
Fetching page 363...
Fetching page 364...
Fetching page 365...
Fetching page 366...
Fetching page 367...
Fetching page 368...
Fetching page 369...
Fetching page 370...
Fetching page 371...
Fetching page 372...
Fetching page 373...
Fetching page 374...
Fetching page 375...
Fetching page 376...
Fetching page 377...
Fetching page 378...
Fetching page 379...
Fetching page 380...
Fetching page 381...
Fetching page 382...
Fetching page 383...
Fetching page 384...
Fetching page 385...
Fetching page 386...
Fetching page 387...
Fetching page 388...
Fetching page 389...
Fetching page 390...
Fetching page 391...
Fetching page 392...
Fetching page 393...
Fetching page 394...
Fetching page 395...
Fetching page 396...
Fetching page 397...
Fetching page 398...
Fetching page 399...
Fetching page 400...
Fetching page 401...
Fetching page 402...
Fetching page 403...
Fetching page 404...
Fetching page 405...
Fetching page 406...
Fetching page 407...
Fetching page 408...
Fetching page 409...
Fetching page 410...
Fetching page 411...
Fetching page 412...
Fetching page 413...
Fetching page 414...
Fetching page 415...
Fetching page 416...
Fetching page 417...
Fetching page 418...
Fetching page 419...
Fetching page 420...
Fetching page 421...
Fetching page 422...
Fetching page 423...
Fetching page 424...
Fetching page 425...
Fetching page 426...
Fetching page 427...
Fetching page 428...
Fetching page 429...
Fetching page 430...
Fetching page 431...
Fetching page 432...
Fetching page 433...
Fetching page 434...
Fetching page 435...
Fetching page 436...
Fetching page 437...
Fetching page 438...
Fetching page 439...
Fetching page 440...
Fetching page 441...
Fetching page 442...
Fetching page 443...
Fetching page 444...
Fetching page 445...
Fetching page 446...
Fetching page 447...
Fetching page 448...
Fetching page 449...
Fetching page 450...
Fetching page 451...
Fetching page 452...
Fetching page 453...
Fetching page 454...
Fetching page 455...
Fetching page 456...
Fetching page 457...
Fetching page 458...
Fetching page 459...
Fetching page 460...
Fetching page 461...
Fetching page 462...
Fetching page 463...
Fetching page 464...
Fetching page 465...
Fetching page 466...
Fetching page 467...
Fetching page 468...
Fetching page 469...
Fetching page 470...
Fetching page 471...
Fetching page 472...
Fetching page 473...
Fetching page 474...
Fetching page 475...
Fetching page 476...
Fetching page 477...
Fetching page 478...
Fetching page 479...
Fetching page 480...
Fetching page 481...
Fetching page 482...
Fetching page 483...
Fetching page 484...
Fetching page 485...
Fetching page 486...
Fetching page 487...
Fetching page 488...
Fetching page 489...
Fetching page 490...
Fetching page 491...
Fetching page 492...
Fetching page 493...
Fetching page 494...
Fetching page 495...
Fetching page 496...
Fetching page 497...
Fetching page 498...
Fetching page 499...
Fetching page 500...
Fetching page 501...
Failed to fetch page 501, status code: 400
Fetching page 502...
Failed to fetch page 502, status code: 400
Fetching page 503...
Failed to fetch page 503, status code: 400
Fetching page 504...
Failed to fetch page 504, status code: 400
Fetching page 505...
Failed to fetch page 505, status code: 400
Fetching page 506...
Failed to fetch page 506, status code: 400
Fetching page 507...
Failed to fetch page 507, status code: 400
Fetching page 508...
Failed to fetch page 508, status code: 400
Fetching page 509...
Failed to fetch page 509, status code: 400
Fetching page 510...
Failed to fetch page 510, status code: 400
Fetching page 511...
Failed to fetch page 511, status code: 400
Fetching page 512...
Failed to fetch page 512, status code: 400
Fetching page 513...
Failed to fetch page 513, status code: 400
Fetching page 514...
Failed to fetch page 514, status code: 400
Fetching page 515...
Failed to fetch page 515, status code: 400
Fetching page 516...
Failed to fetch page 516, status code: 400
Fetching page 517...
Failed to fetch page 517, status code: 400
Fetching page 518...
Failed to fetch page 518, status code: 400
Fetching page 519...
Failed to fetch page 519, status code: 400
Fetching page 520...
Failed to fetch page 520, status code: 400
Fetching page 521...
Failed to fetch page 521, status code: 400
Fetching page 522...
Failed to fetch page 522, status code: 400
Fetching page 523...
Failed to fetch page 523, status code: 400
Fetching page 524...
Failed to fetch page 524, status code: 400
Fetching page 525...
Failed to fetch page 525, status code: 400
Fetching page 526...
Failed to fetch page 526, status code: 400
Fetching page 527...
Failed to fetch page 527, status code: 400
Fetching page 528...
Failed to fetch page 528, status code: 400
Fetching page 529...
Failed to fetch page 529, status code: 400
Fetching page 530...
Failed to fetch page 530, status code: 400
Fetching page 531...
Failed to fetch page 531, status code: 400
Fetching page 532...
Failed to fetch page 532, status code: 400
Fetching page 533...
Failed to fetch page 533, status code: 400
Fetching page 534...
Failed to fetch page 534, status code: 400
Fetching page 535...
Failed to fetch page 535, status code: 400
Fetching page 536...
Failed to fetch page 536, status code: 400
Fetching page 537...
Failed to fetch page 537, status code: 400
Fetching page 538...
Failed to fetch page 538, status code: 400
Fetching page 539...
Failed to fetch page 539, status code: 400
Fetching page 540...
Failed to fetch page 540, status code: 400
Fetching page 541...
Failed to fetch page 541, status code: 400
Fetching page 542...
Failed to fetch page 542, status code: 400
Fetching page 543...
Failed to fetch page 543, status code: 400
Fetching page 544...
Failed to fetch page 544, status code: 400
Fetching page 545...
Failed to fetch page 545, status code: 400
Fetching page 546...
Failed to fetch page 546, status code: 400
Fetching page 547...
Failed to fetch page 547, status code: 400
Fetching page 548...
Failed to fetch page 548, status code: 400
Fetching page 549...
Failed to fetch page 549, status code: 400
Fetching page 550...
Failed to fetch page 550, status code: 400
Fetching page 551...
Failed to fetch page 551, status code: 400
Fetching page 552...
Failed to fetch page 552, status code: 400
Fetching page 553...
Failed to fetch page 553, status code: 400
Fetching page 554...
Failed to fetch page 554, status code: 400
Fetching page 555...
Failed to fetch page 555, status code: 400
Fetching page 556...
Failed to fetch page 556, status code: 400
Fetching page 557...
Failed to fetch page 557, status code: 400
Fetching page 558...
Failed to fetch page 558, status code: 400
Fetching page 559...
Failed to fetch page 559, status code: 400
Fetching page 560...
Failed to fetch page 560, status code: 400
Fetching page 561...
Failed to fetch page 561, status code: 400
Fetching page 562...
Failed to fetch page 562, status code: 400
Fetching page 563...
Failed to fetch page 563, status code: 400
Fetching page 564...
Failed to fetch page 564, status code: 400
Fetching page 565...
Failed to fetch page 565, status code: 400
Fetching page 566...
Failed to fetch page 566, status code: 400
Fetching page 567...
Failed to fetch page 567, status code: 400
Fetching page 568...
Failed to fetch page 568, status code: 400
Fetching page 569...
Failed to fetch page 569, status code: 400
Fetching page 570...
Failed to fetch page 570, status code: 400
Fetching page 571...
Failed to fetch page 571, status code: 400
Fetching page 572...
Failed to fetch page 572, status code: 400
Fetching page 573...
Failed to fetch page 573, status code: 400
Fetching page 574...
Failed to fetch page 574, status code: 400
Fetching page 575...
Failed to fetch page 575, status code: 400
Fetching page 576...
Failed to fetch page 576, status code: 400
Fetching page 577...
Failed to fetch page 577, status code: 400
Fetching page 578...
Failed to fetch page 578, status code: 400
Fetching page 579...
Failed to fetch page 579, status code: 400
Fetching page 580...
Failed to fetch page 580, status code: 400
Fetching page 581...
Failed to fetch page 581, status code: 400
Fetching page 582...
Failed to fetch page 582, status code: 400
Fetching page 583...
Failed to fetch page 583, status code: 400
Fetching page 584...
Failed to fetch page 584, status code: 400
Fetching page 585...
Failed to fetch page 585, status code: 400
Fetching page 586...
Failed to fetch page 586, status code: 400
Fetching page 587...
Failed to fetch page 587, status code: 400
Fetching page 588...
Failed to fetch page 588, status code: 400
Fetching page 589...
Failed to fetch page 589, status code: 400
Fetching page 590...
Failed to fetch page 590, status code: 400
Fetching page 591...
Failed to fetch page 591, status code: 400
Fetching page 592...
Failed to fetch page 592, status code: 400
Fetching page 593...
Failed to fetch page 593, status code: 400
Fetching page 594...
Failed to fetch page 594, status code: 400
Fetching page 595...
Failed to fetch page 595, status code: 400
Fetching page 596...
Failed to fetch page 596, status code: 400
Fetching page 597...
Failed to fetch page 597, status code: 400
Fetching page 598...
Failed to fetch page 598, status code: 400
Fetching page 599...
Failed to fetch page 599, status code: 400
Fetching page 600...
Failed to fetch page 600, status code: 400
Fetching page 601...
Failed to fetch page 601, status code: 400
Fetching page 602...
Failed to fetch page 602, status code: 400
Fetching page 603...
Failed to fetch page 603, status code: 400
Fetching page 604...
Failed to fetch page 604, status code: 400
Fetching page 605...
Failed to fetch page 605, status code: 400
Fetching page 606...
Failed to fetch page 606, status code: 400
Fetching page 607...
Failed to fetch page 607, status code: 400
Fetching page 608...
Failed to fetch page 608, status code: 400
Fetching page 609...
Failed to fetch page 609, status code: 400
Fetching page 610...
Failed to fetch page 610, status code: 400
Fetching page 611...
Failed to fetch page 611, status code: 400
Fetching page 612...
Failed to fetch page 612, status code: 400
Fetching page 613...
Failed to fetch page 613, status code: 400
Fetching page 614...
Failed to fetch page 614, status code: 400
Fetching page 615...
Failed to fetch page 615, status code: 400
Fetching page 616...
Failed to fetch page 616, status code: 400
Fetching page 617...
Failed to fetch page 617, status code: 400
Fetching page 618...
Failed to fetch page 618, status code: 400
Fetching page 619...
Failed to fetch page 619, status code: 400
Fetching page 620...
Failed to fetch page 620, status code: 400
Fetching page 621...
Failed to fetch page 621, status code: 400
Fetching page 622...
Failed to fetch page 622, status code: 400
Fetching page 623...
Failed to fetch page 623, status code: 400
Fetching page 624...
Failed to fetch page 624, status code: 400
Fetching page 625...
Failed to fetch page 625, status code: 400
Fetching page 626...
Failed to fetch page 626, status code: 400
Fetching page 627...
Failed to fetch page 627, status code: 400
Fetching page 628...
Failed to fetch page 628, status code: 400
Fetching page 629...
Failed to fetch page 629, status code: 400
Fetching page 630...
Failed to fetch page 630, status code: 400
Fetching page 631...
Failed to fetch page 631, status code: 400
Fetching page 632...
Failed to fetch page 632, status code: 400
Fetching page 633...
Failed to fetch page 633, status code: 400
Fetching page 634...
Failed to fetch page 634, status code: 400
Fetching page 635...
Failed to fetch page 635, status code: 400
Fetching page 636...
Failed to fetch page 636, status code: 400
Fetching page 637...
Failed to fetch page 637, status code: 400
Fetching page 638...
Failed to fetch page 638, status code: 400
Fetching page 639...
Failed to fetch page 639, status code: 400
Fetching page 640...
Failed to fetch page 640, status code: 400
Fetching page 641...
Failed to fetch page 641, status code: 400
Fetching page 642...
Failed to fetch page 642, status code: 400
Fetching page 643...
Failed to fetch page 643, status code: 400
Fetching page 644...
Failed to fetch page 644, status code: 400
Fetching page 645...
Failed to fetch page 645, status code: 400
Fetching page 646...
Failed to fetch page 646, status code: 400
Fetching page 647...
Failed to fetch page 647, status code: 400
Fetching page 648...
Failed to fetch page 648, status code: 400
Fetching page 649...
Failed to fetch page 649, status code: 400
Fetching page 650...
Failed to fetch page 650, status code: 400

In [3]:
df

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,44.5978,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,The Shawshank Redemption,False,8.709,28215
1,False,/tmU7GeKVybMWFButWEGl2M4GeiP.jpg,"[18, 80]",238,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",33.9749,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,The Godfather,False,8.687,21390
2,False,/xyWKrni8WrYzqn7ztvI5nIY0h62.jpg,"[35, 10749]",1181678,en,¿Quieres ser mi hijo?,"Lu, a conformist woman in her forties, learns ...",2.1586,/9GuvODahvuFqdhuZ16aBLR4UJoP.jpg,2023-09-21,¿Quieres ser mi hijo?,False,8.576,284
3,False,/kGzFbGhp99zva6oZODW5atUtnqi.jpg,"[18, 80]",240,en,The Godfather Part II,In the continuing saga of the Corleone crime f...,15.2780,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,The Godfather Part II,False,8.571,12923
4,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[18, 36, 10752]",424,en,Schindler's List,The true story of how businessman Oskar Schind...,40.5468,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,Schindler's List,False,8.565,16396
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,False,/mEbTaD4s455YAXqzG032239azrV.jpg,[35],58013,it,La banda dei Babbi Natale,"On Christmas Eve, three friends dressed as San...",0.9498,/uPiRMJ2JrIy7ouEmoUcy7Q8rlub.jpg,2010-12-17,The Santa Claus Gang,False,6.026,1054
9996,False,/oi9RFxqb5Tncm7VvDnVT6sZUWyH.jpg,"[18, 53]",27526,en,The Crossing Guard,Unable to move on from the loss of his daughte...,4.9305,/kogaCIIylHmWQo2gJrrdq8Br8b8.jpg,1995-01-26,The Crossing Guard,False,6.000,266
9997,False,/hlPOs551MEegrr6M3yYATBWy58e.jpg,"[10751, 16, 12, 35]",13654,en,101 Dalmatians II: Patch's London Adventure,"Being one of 101 takes its toll on Patch, who ...",2.9521,/rFTt7pNSCJKLZ2RZldJuq6ON6Ti.jpg,2003-03-02,101 Dalmatians II: Patch's London Adventure,False,6.026,1188
9998,False,/mPId0j7owQmeOQHyOl2kEbzQpXd.jpg,"[35, 28, 80]",9416,en,Money Talks,"Sought by police and criminals, a small-time h...",7.2760,/bN57Rl003E9pYred5kw9Rp8h9Np.jpg,1997-08-22,Money Talks,False,6.026,392
9999,False,/6hQgTpZVNHrLafE6IeSAoThQwkH.jpg,"[14, 53, 18]",8884,en,Franklyn,Set between the parallel worlds of contemporar...,4.6225,/5yns10om8I19j4OHy1zoVRilAnw.jpg,2008-10-16,Franklyn,False,6.000,360

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   adult              10000 non-null  bool
 1   backdrop_path      9985 non-null   object
 2   genre_ids          10000 non-null  object
 3   id                 10000 non-null  int64
 4   original_language  10000 non-null  object
 5   original_title     10000 non-null  object
 6   overview           10000 non-null  object
 7   popularity         10000 non-null  float64
 8   poster_path        9993 non-null   object
 9   release_date       10000 non-null  object
 10  title              10000 non-null  object
 11  video              10000 non-null  bool
 12  vote_average       10000 non-null  float64
 13  vote_count         10000 non-null  int64
dtypes: bool(2), float64(2), int64(2), object(8)
memory usage: 957.2+ KB

# Web Scrapping

## Fetching Genre name through Web Scrapping

In [5]:
# now creating new column on the basis of genre_ids

#### we have genre_ids relation on other page of website so scraped the data to create new column

In [63]:
from bs4 import BeautifulSoup

# Example HTML (this should be your website code loaded as string)
html_code = '''
<ul id="with_genres" class="multi_select text" name="with_genres[]">
                    <li data-value="28"><a class="no_click" href="/discover/movie?with_genres=28">Action</a></li>
                    <li data-value="12"><a class="no_click" href="/discover/movie?with_genres=12">Adventure</a></li>
                    <li data-value="16"><a class="no_click" href="/discover/movie?with_genres=16">Animation</a></li>
                    <li data-value="35"><a class="no_click" href="/discover/movie?with_genres=35">Comedy</a></li>
                    <li data-value="80"><a class="no_click" href="/discover/movie?with_genres=80">Crime</a></li>
                    <li data-value="99"><a class="no_click" href="/discover/movie?with_genres=99">Documentary</a></li>
                    <li data-value="18"><a class="no_click" href="/discover/movie?with_genres=18">Drama</a></li>
                    <li data-value="10751"><a class="no_click" href="/discover/movie?with_genres=10751">Family</a></li>
                    <li data-value="14"><a class="no_click" href="/discover/movie?with_genres=14">Fantasy</a></li>
                    <li data-value="36"><a class="no_click" href="/discover/movie?with_genres=36">History</a></li>
                    <li data-value="27"><a class="no_click" href="/discover/movie?with_genres=27">Horror</a></li>
                    <li data-value="10402"><a class="no_click" href="/discover/movie?with_genres=10402">Music</a></li>
                    <li data-value="9648"><a class="no_click" href="/discover/movie?with_genres=9648">Mystery</a></li>
                    <li data-value="10749"><a class="no_click" href="/discover/movie?with_genres=10749">Romance</a></li>
                    <li data-value="878"><a class="no_click" href="/discover/movie?with_genres=878">Science Fiction</a></li>
                    <li data-value="10770"><a class="no_click" href="/discover/movie?with_genres=10770">TV Movie</a></li>
                    <li data-value="53"><a class="no_click" href="/discover/movie?with_genres=53">Thriller</a></li>
                    <li data-value="10752"><a class="no_click" href="/discover/movie?with_genres=10752">War</a></li>
                    <li data-value="37"><a class="no_click" href="/discover/movie?with_genres=37">Western</a></li>
                </ul>
'''

# Step 1: Parse the HTML
soup = BeautifulSoup(html_code, 'html.parser')

# Step 2: Find all <li> elements
li_tags = soup.find_all('li')
# Step 3: Create dictionary from data
genre_mapping = {}
for li in li_tags:
    genre_id = int(li['data-value'])  # get data-value attribute
    genre_name = li.get_text(strip=True)  # get visible text (the genre name)
    genre_mapping[genre_id] = genre_name

# Step 4: Print the extracted dictionary
print(genre_mapping)

{28: 'Action', 12: 'Adventure', 16: 'Animation', 35: 'Comedy', 80: 'Crime', 99: 'Documentary', 18: 'Drama', 10751: 'Family', 14: 'Fantasy', 36: 'History', 27: 'Horror', 10402: 'Music', 9648: 'Mystery', 10749: 'Romance', 878: 'Science Fiction', 10770: 'TV Movie', 53: 'Thriller', 10752: 'War', 37: 'Western'}

In [7]:
## Now adding genre_name column in data as relation of genre_ids

In [8]:
def map_genre_ids_to_names(genre_ids):
    return [genre_mapping.get(genre_id, "Unknown") for genre_id in genre_ids]

# Create a new column 'genre_names'
df['genre_names'] = df['genre_ids'].apply(map_genre_ids_to_names)

In [9]:
df

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count,genre_names
0,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,44.5978,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,The Shawshank Redemption,False,8.709,28215,"[Drama, Crime]"
1,False,/tmU7GeKVybMWFButWEGl2M4GeiP.jpg,"[18, 80]",238,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",33.9749,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,The Godfather,False,8.687,21390,"[Drama, Crime]"
2,False,/xyWKrni8WrYzqn7ztvI5nIY0h62.jpg,"[35, 10749]",1181678,en,¿Quieres ser mi hijo?,"Lu, a conformist woman in her forties, learns ...",2.1586,/9GuvODahvuFqdhuZ16aBLR4UJoP.jpg,2023-09-21,¿Quieres ser mi hijo?,False,8.576,284,"[Comedy, Romance]"
3,False,/kGzFbGhp99zva6oZODW5atUtnqi.jpg,"[18, 80]",240,en,The Godfather Part II,In the continuing saga of the Corleone crime f...,15.2780,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,The Godfather Part II,False,8.571,12923,"[Drama, Crime]"
4,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[18, 36, 10752]",424,en,Schindler's List,The true story of how businessman Oskar Schind...,40.5468,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,Schindler's List,False,8.565,16396,"[Drama, History, War]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,False,/mEbTaD4s455YAXqzG032239azrV.jpg,[35],58013,it,La banda dei Babbi Natale,"On Christmas Eve, three friends dressed as San...",0.9498,/uPiRMJ2JrIy7ouEmoUcy7Q8rlub.jpg,2010-12-17,The Santa Claus Gang,False,6.026,1054,[Comedy]
9996,False,/oi9RFxqb5Tncm7VvDnVT6sZUWyH.jpg,"[18, 53]",27526,en,The Crossing Guard,Unable to move on from the loss of his daughte...,4.9305,/kogaCIIylHmWQo2gJrrdq8Br8b8.jpg,1995-01-26,The Crossing Guard,False,6.000,266,"[Drama, Thriller]"
9997,False,/hlPOs551MEegrr6M3yYATBWy58e.jpg,"[10751, 16, 12, 35]",13654,en,101 Dalmatians II: Patch's London Adventure,"Being one of 101 takes its toll on Patch, who ...",2.9521,/rFTt7pNSCJKLZ2RZldJuq6ON6Ti.jpg,2003-03-02,101 Dalmatians II: Patch's London Adventure,False,6.026,1188,"[Family, Animation, Adventure, Comedy]"
9998,False,/mPId0j7owQmeOQHyOl2kEbzQpXd.jpg,"[35, 28, 80]",9416,en,Money Talks,"Sought by police and criminals, a small-time h...",7.2760,/bN57Rl003E9pYred5kw9Rp8h9Np.jpg,1997-08-22,Money Talks,False,6.026,392,"[Comedy, Action, Crime]"
9999,False,/6hQgTpZVNHrLafE6IeSAoThQwkH.jpg,"[14, 53, 18]",8884,en,Franklyn,Set between the parallel worlds of contemporar...,4.6225,/5yns10om8I19j4OHy1zoVRilAnw.jpg,2008-10-16,Franklyn,False,6.000,360,"[Fantasy, Thriller, Drama]"

# Cleaning the data as per requirment

In [14]:
# creating a copy
data = df.copy()
data.sample(30)

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count,genre_names
4003,False,/bycLClGKY8fWkHKggzzNLNczoXn.jpg,"[28, 35, 53]",10616,cn,殺手之王,"Financially troubled, a newbie hitman reluctan...",2.4990,/3zSsfOuO5kIVrOIDxcmFr7zMXxI.jpg,1998-04-03,Contract Killer,False,7.015,234,"[Action, Comedy, Thriller]"
687,False,/h1vBJ0uN4QCbBb5WVKxmtfTrHoY.jpg,[37],11697,en,The Man Who Shot Liberty Valance,Questions arise when Senator Stoddard attends ...,3.1240,/4C1R0LEivLjbv3swAzJfzh0tzXl.jpg,1962-04-13,The Man Who Shot Liberty Valance,False,7.800,1183,[Western]
1996,False,/iM267DzAdcndC4vqOTbJxUPIpzK.jpg,"[14, 16, 28, 53, 10751]",50337,en,Firebreather,It's not easy being a teen like Duncan. His mo...,4.5809,/SAVggPzEtiS4zYfq5ELJkrL3s3.jpg,2010-11-24,Firebreather,False,7.389,217,"[Fantasy, Animation, Action, Thriller, Family]"
6398,False,/njK3bfEYuqwjs8YTkpaDtkoTmVr.jpg,"[18, 35]",239678,en,This Is Where I Leave You,"When their father passes away, four grown, wor...",7.3322,/rVUI2267FdetVWz9UBQbqTmRVhQ.jpg,2014-09-10,This Is Where I Leave You,False,6.632,1371,"[Drama, Comedy]"
1715,False,/uBeMRYy7ZYQ76oVuQN8lrKx9c37.jpg,"[12, 10751]",589982,fr,Donne-moi des ailes,"Christian, a visionary scientist, studies wild...",1.5205,/y6GqD6MabPjvPrJeTmRmgd896Py.jpg,2019-09-12,Spread Your Wings,False,7.500,304,"[Adventure, Family]"
8600,False,/a9VOWosINcLNJQb3hNZAqEShVTM.jpg,"[10749, 18, 35]",1378,en,Shortbus,"In post-9/11 New York City, an eclectic group ...",4.7897,/s8QBrWgpZpYrySSyTQ0xbFLPKrS.jpg,2006-10-04,Shortbus,False,6.272,528,"[Romance, Drama, Comedy]"
2649,False,/7cdsVkbs7tAuZJwJRYb65dN5kMv.jpg,"[16, 10751]",286192,en,Lava,Inspired by the isolated beauty of tropical is...,2.4958,/blZSkXNN4CzRBxdxXnz3YpUjnJp.jpg,2014-10-10,Lava,False,7.258,1088,"[Animation, Family]"
7235,False,/rmB13CFLNFJIML8VLTnzDjMcmsC.jpg,"[16, 35, 10751]",161143,en,Madly Madagascar,Your favorite Madagascar pals are back in an a...,2.3910,/1M8J7tpy5Vnkewp1BFS82abGOFD.jpg,2013-01-29,Madly Madagascar,False,6.500,236,"[Animation, Comedy, Family]"
29,False,/qUq3QTr2KLvGIcN0GaaaYx9bbyH.jpg,[18],510,en,One Flew Over the Cuckoo's Nest,A petty criminal fakes insanity to serve his s...,18.4679,/kjWsMh72V6d8KRLV4EOoSJLT1H7.jpg,1975-11-19,One Flew Over the Cuckoo's Nest,False,8.414,10738,[Drama]
1151,False,/hNCqkXbWd40eftqSdjq8TmV7Mqr.jpg,"[18, 878, 9648]",329865,en,Arrival,Taking place after alien crafts land around th...,14.0969,/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg,2016-11-10,Arrival,False,7.612,18201,"[Drama, Science Fiction, Mystery]"
2001,False,/sI6uCeF8mUlZx22mFfHSi9W3XQ9.jpg,"[10749, 18, 35]",843527,en,The Idea of You,40-year-old single mom Solène begins an unexpe...,21.9556,/Y5P4Q3q8nrruZ9aD3wXeJS2Plg.jpg,2024-05-02,The Idea of You,False,7.387,1664,"[Romance, Drama, Comedy]"
200,False,/4JNggqfyJWREqb0enzpUMbvIniV.jpg,"[16, 10751, 35, 14]",508442,en,Soul,Joe Gardner is a middle school teacher with a ...,20.5326,/pEz5aROvfy5FBW1OTlrDO3VryWO.jpg,2020-12-25,Soul,False,8.110,10736,"[Animation, Family, Comedy, Fantasy]"
4709,False,/zKeTLUB5obmb0DPqqqtm3k0Mfbm.jpg,[37],11842,fr,Soleil Rouge,"In 1870, Japanese ambassador Sakaguchi and his...",2.4633,/hDQyx0N8J5OJMJYpJLIX0SkKwT4.jpg,1971-09-15,Red Sun,False,6.900,276,[Western]
47,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,"[28, 878, 12]",27205,en,Inception,"Cobb, a skilled thief who commits corporate es...",28.7509,/ljsZTbVsrQSqZgWeep2B1QiDKuh.jpg,2010-07-15,Inception,False,8.368,37409,"[Action, Science Fiction, Adventure]"
6638,False,/4xAxAvrcnelGOBA5mQsW0aEHpqW.jpg,"[18, 28, 53]",4105,en,Black Rain,Two New York cops get involved in a gang war b...,7.0694,/funhGWt9ee3Uwb6Ar8SGCCvbJdV.jpg,1989-09-22,Black Rain,False,6.591,1127,"[Drama, Action, Thriller]"
8917,False,/2TlVQC5s6veC9MZSIj9K2Drrb.jpg,"[18, 35]",82532,en,"Jeff, Who Lives at Home",Dispatched from his basement room on an errand...,5.6452,/eh8KzVUzOeZES67FPjO8NktLtY7.jpg,2012-03-16,"Jeff, Who Lives at Home",False,6.216,644,"[Drama, Comedy]"
9924,False,/nKXnqssHmh6miZU3jyG5Mz1jpQ3.jpg,"[27, 14, 9648]",254194,en,Starry Eyes,A hopeful young starlet uncovers the ominous o...,0.8778,/t1sIumVCl91XThMoJqUjpERYeAM.jpg,2014-07-29,Starry Eyes,False,6.040,458,"[Horror, Fantasy, Mystery]"
4920,False,/vMkeEe73U2l11T7udziysLzBRg9.jpg,"[16, 10751, 14, 10749]",16962,en,Barbie Fairytopia: Magic of the Rainbow,Elina goes to a fairy school to learn dancing ...,5.9965,/suo0EcRi0uJNRlhmNqOuDHpCSSE.jpg,2007-03-13,Barbie Fairytopia: Magic of the Rainbow,False,6.867,447,"[Animation, Family, Fantasy, Romance]"
7206,False,/cbtNuNDGgOw1CHqtM8oLK5odfLz.jpg,"[18, 36]",309299,en,Experimenter,"Yale University, 1961. Stanley Milgram designs...",6.6923,/kMTLGbekuHkpw4M8XKdN2d7n2aF.jpg,2015-10-16,Experimenter,False,6.496,461,"[Drama, History]"
4565,False,/tRSqRppPkWEoztjX97D8bjWQa8C.jpg,[35],778,fr,Les vacances de Monsieur Hulot,"Monsieur Hulot, Jacques Tati’s endearing clown...",3.3852,/r4F4tsU0Ajeh9ZYUkWOJSYmioj7.jpg,1953-02-25,Monsieur Hulot's Holiday,False,6.924,481,[Comedy]
2445,False,/f133nWlU6yUkZqqwcCXCbTEJWHr.jpg,"[12, 28]",87,en,Indiana Jones and the Temple of Doom,"After arriving in India, Indiana Jones is aske...",19.0084,/om61eim8XwLfh6QXzh2r0Q4blBz.jpg,1984-05-23,Indiana Jones and the Temple of Doom,False,7.296,9501,"[Adventure, Action]"
1729,False,/jhM3wgWUrrOkz9r4xwV5cV5RhI4.jpg,[878],17654,en,District 9,"Thirty years ago, aliens arrive on Earth. Not ...",7.5209,/tuGlQkqLxnodDSk6mp5c2wvxUEd.jpg,2009-08-05,District 9,False,7.449,9714,[Science Fiction]
7671,False,/wP28rWRjcD1994uSLXAg0MZmUK7.jpg,"[35, 18]",790496,ro,Babardeala cu bucluc sau porno balamuc,"Emi, a school teacher, finds her career and re...",0.2872,/zUTkjET8VUwvbvSHtn0Lou7xwyZ.jpg,2021-04-29,Bad Luck Banging or Loony Porn,False,6.423,227,"[Comedy, Drama]"
7214,False,/k6BDdDhWeTlj0LVUL5eADZtR0cz.jpg,"[18, 10749]",535,en,Flashdance,"Alex Owens, a young woman juggling between two...",7.8076,/ziiy6ORt8BlxWFXskBChBMInvDA.jpg,1983-04-14,Flashdance,False,6.496,1503,"[Drama, Romance]"
9585,False,/lyt9DYP0Suy1j8XnjJl0saVOs8K.jpg,"[12, 16, 10751, 35, 878]",278154,en,Ice Age: Collision Course,"Set after the events of Continental Drift, Scr...",7.8044,/dWyaaP1dmW5peBvgiVaugdRuyYD.jpg,2016-06-23,Ice Age: Collision Course,False,6.100,4646,"[Adventure, Animation, Family, Comedy, Science..."
1730,False,/wePpxpU1eNZnHCChP5xGNJrGKY3.jpg,"[10751, 18]",339984,en,Miracles from Heaven,When Christy discovers her 10-year-old daughte...,11.7571,/hz9VF1TfaM0D04pYneSXUkNeOZv.jpg,2016-03-17,Miracles from Heaven,False,7.448,1204,"[Family, Drama]"
8056,False,/Q3baW7mlwITGGb7pA7fGQSVqQ3.jpg,"[53, 18]",846956,en,Rogue Agent,Conman Robert Freegard poses as an undercover ...,4.7405,/4tOaGR6mzUAEQzIgWCeVoneRIkp.jpg,2022-08-12,Rogue Agent,False,6.360,221,"[Thriller, Drama]"
2803,False,/sxj8EsehEt295QcqoF7g6VzX36p.jpg,[18],425373,en,The Miracle Season,After the tragic death of star volleyball play...,4.5209,/cIVYjwi8QcZ9AQk4WRYgW4iUmXb.jpg,2018-04-13,The Miracle Season,False,7.200,307,[Drama]
5050,False,/nE7p7AgZtRmQdEu7Z275f4729k2.jpg,"[28, 80, 53]",11018,en,Year of the Dragon,"In New York, racist Capt. Stanley White become...",1.4744,/c8SfIgwR5mfu0c0qTBKbsvBfecJ.jpg,1985-08-16,Year of the Dragon,False,6.846,436,"[Action, Crime, Thriller]"
8044,False,/zqNOCCVhZRjryQ7BcvpIHTY10Uf.jpg,"[27, 9648]",24274,en,Dead & Buried,After a series of gory murders commited by mob...,1.1493,/aMZD57u1M9TQAKf12OYUUcv9hjn.jpg,1981-05-29,Dead & Buried,False,6.362,297,"[Horror, Mystery]"

In [13]:
# checking info
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   adult              10000 non-null  bool
 1   backdrop_path      9985 non-null   object
 2   genre_ids          10000 non-null  object
 3   id                 10000 non-null  int64
 4   original_language  10000 non-null  object
 5   original_title     10000 non-null  object
 6   overview           10000 non-null  object
 7   popularity         10000 non-null  float64
 8   poster_path        9993 non-null   object
 9   release_date       10000 non-null  object
 10  title              10000 non-null  object
 11  video              10000 non-null  bool
 12  vote_average       10000 non-null  float64
 13  vote_count         10000 non-null  int64
 14  genre_names        10000 non-null  object
dtypes: bool(2), float64(2), int64(2), object(9)
memory usage: 1.0+ MB

In [17]:
# keeping those columns which needs for visulaization
data.drop(columns = ['backdrop_path', 'genre_ids', 'overview', 'poster_path', 'video'],inplace = True)

In [18]:
data.head()

,adult,id,original_language,original_title,popularity,release_date,title,vote_average,vote_count,genre_names
0,False,278,en,The Shawshank Redemption,44.5978,1994-09-23,The Shawshank Redemption,8.709,28215,"[Drama, Crime]"
1,False,238,en,The Godfather,33.9749,1972-03-14,The Godfather,8.687,21390,"[Drama, Crime]"
2,False,1181678,en,¿Quieres ser mi hijo?,2.1586,2023-09-21,¿Quieres ser mi hijo?,8.576,284,"[Comedy, Romance]"
3,False,240,en,The Godfather Part II,15.2780,1974-12-20,The Godfather Part II,8.571,12923,"[Drama, Crime]"
4,False,424,en,Schindler's List,40.5468,1993-12-15,Schindler's List,8.565,16396,"[Drama, History, War]"

In [19]:
# now the dataset don't have any missing values

In [28]:
# now changing release_date type from object to datetime
data['release_date'] = pd.to_datetime(df['release_date'])

In [29]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   adult              10000 non-null  bool
 1   id                 10000 non-null  int64
 2   original_language  10000 non-null  object
 3   original_title     10000 non-null  object
 4   popularity         10000 non-null  float64
 5   release_date       9998 non-null   datetime64[ns]
 6   title              10000 non-null  object
 7   vote_average       10000 non-null  float64
 8   vote_count         10000 non-null  int64
 9   genre_names        10000 non-null  object
dtypes: bool(1), datetime64[ns](1), float64(2), int64(2), object(4)
memory usage: 713.0+ KB

In [40]:
# now working on genre_names column
data['genre_names'] = data['genre_names'].astype(str).str.lstrip("['").str.rstrip("']").str.replace("', '","|")

In [41]:
data

,adult,id,original_language,original_title,popularity,release_date,title,vote_average,vote_count,genre_names
0,False,278,en,The Shawshank Redemption,44.5978,1994-09-23,The Shawshank Redemption,8.709,28215,Drama|Crime
1,False,238,en,The Godfather,33.9749,1972-03-14,The Godfather,8.687,21390,Drama|Crime
2,False,1181678,en,¿Quieres ser mi hijo?,2.1586,2023-09-21,¿Quieres ser mi hijo?,8.576,284,Comedy|Romance
3,False,240,en,The Godfather Part II,15.2780,1974-12-20,The Godfather Part II,8.571,12923,Drama|Crime
4,False,424,en,Schindler's List,40.5468,1993-12-15,Schindler's List,8.565,16396,Drama|History|War
...,...,...,...,...,...,...,...,...,...,...
9995,False,58013,it,La banda dei Babbi Natale,0.9498,2010-12-17,The Santa Claus Gang,6.026,1054,Comedy
9996,False,27526,en,The Crossing Guard,4.9305,1995-01-26,The Crossing Guard,6.000,266,Drama|Thriller
9997,False,13654,en,101 Dalmatians II: Patch's London Adventure,2.9521,2003-03-02,101 Dalmatians II: Patch's London Adventure,6.026,1188,Family|Animation|Adventure|Comedy
9998,False,9416,en,Money Talks,7.2760,1997-08-22,Money Talks,6.026,392,Comedy|Action|Crime
9999,False,8884,en,Franklyn,4.6225,2008-10-16,Franklyn,6.000,360,Fantasy|Thriller|Drama

In [45]:
df['original_language'].unique()

array(['en', 'ja', 'hi', 'ko', 'it', 'pt', 'es', 'zh', 'fr', 'tr', 'ru',
       'lv', 'sv', 'ar', 'hu', 'de', 'cn', 'bn', 'th', 'da', 'pl', 'nl',
       'fa', 'xx', 'cs', 'te', 'sr', 'ku', 'et', 'sh', 'uk', 'ml', 'id',
       'ro', 'gl', 'bs', 'el', 'ga', 'no', 'fi', 'kn', 'ta', 'hy', 'ka',
       'is', 'ca', 'la', 'sk', 'tn', 'eu', 'mk', 'he', 'km'], dtype=object)

In [46]:
# replacing language codes with it's full name
lang_map = {
    'en': 'English',
    'hi': 'Hindi',
    'ja': 'Japanese',
    'ko': 'Korean',
    'it': 'Italian',
    'pt': 'Portuguese',
    'es': 'Spanish',
    'zh': 'Chinese',
    'fr': 'French',
    'tr': 'Turkish',
    'ru': 'Russian',
    'lv': 'Latvian',
    'sv': 'Swedish',
    'ar': 'Arabic',
    'hu': 'Hungarian',
    'de': 'German',
    'cn': 'Chinese',
    'bn': 'Bengali',
    'th': 'Thai',
    'da': 'Danish',
    'pl': 'Polish',
    'nl': 'Dutch',
    'fa': 'Persian',
    'xx': 'No Language',
    'cs': 'Czech',
    'te': 'Telugu',
    'sr': 'Serbian',
    'ku': 'Kurdish',
    'et': 'Estonian',
    'sh': 'Serbo-Croatian',
    'uk': 'Ukrainian',
    'ml': 'Malayalam',
    'id': 'Indonesian',
    'ro': 'Romanian',
    'gl': 'Galician',
    'bs': 'Bosnian',
    'el': 'Greek',
    'ga': 'Irish',
    'no': 'Norwegian',
    'fi': 'Finnish',
    'kn': 'Kannada',
    'ta': 'Tamil',
    'hy': 'Armenian',
    'ka': 'Georgian',
    'is': 'Icelandic',
    'ca': 'Catalan',
    'la': 'Latin',
    'sk': 'Slovak',
    'tn': 'Tswana',
    'eu': 'Basque',
    'mk': 'Macedonian',
    'he': 'Hebrew',
    'km': 'Khmer'
}

data['original_language'] = data['original_language'].map(lang_map)

In [47]:
data

,adult,id,original_language,original_title,popularity,release_date,title,vote_average,vote_count,genre_names
0,False,278,English,The Shawshank Redemption,44.5978,1994-09-23,The Shawshank Redemption,8.709,28215,Drama|Crime
1,False,238,English,The Godfather,33.9749,1972-03-14,The Godfather,8.687,21390,Drama|Crime
2,False,1181678,English,¿Quieres ser mi hijo?,2.1586,2023-09-21,¿Quieres ser mi hijo?,8.576,284,Comedy|Romance
3,False,240,English,The Godfather Part II,15.2780,1974-12-20,The Godfather Part II,8.571,12923,Drama|Crime
4,False,424,English,Schindler's List,40.5468,1993-12-15,Schindler's List,8.565,16396,Drama|History|War
...,...,...,...,...,...,...,...,...,...,...
9995,False,58013,Italian,La banda dei Babbi Natale,0.9498,2010-12-17,The Santa Claus Gang,6.026,1054,Comedy
9996,False,27526,English,The Crossing Guard,4.9305,1995-01-26,The Crossing Guard,6.000,266,Drama|Thriller
9997,False,13654,English,101 Dalmatians II: Patch's London Adventure,2.9521,2003-03-02,101 Dalmatians II: Patch's London Adventure,6.026,1188,Family|Animation|Adventure|Comedy
9998,False,9416,English,Money Talks,7.2760,1997-08-22,Money Talks,6.026,392,Comedy|Action|Crime
9999,False,8884,English,Franklyn,4.6225,2008-10-16,Franklyn,6.000,360,Fantasy|Thriller|Drama

In [49]:
data.rename(columns={'title':'movie_name','genre_names':'genre'},inplace=True)

In [55]:
data.head(2)

,id,movie_name,genre,release_date,original_title,original_language,popularity,vote_average,vote_count,adult
0,278,The Shawshank Redemption,Drama|Crime,1994-09-23,The Shawshank Redemption,English,44.5978,8.709,28215,False
1,238,The Godfather,Drama|Crime,1972-03-14,The Godfather,English,33.9749,8.687,21390,False

In [52]:
# reordring the columns
data = data[['id','movie_name','genre','release_date','original_title','original_language','popularity','vote_average','vote_count','adult']]

In [56]:
data

,id,movie_name,genre,release_date,original_title,original_language,popularity,vote_average,vote_count,adult
0,278,The Shawshank Redemption,Drama|Crime,1994-09-23,The Shawshank Redemption,English,44.5978,8.709,28215,False
1,238,The Godfather,Drama|Crime,1972-03-14,The Godfather,English,33.9749,8.687,21390,False
2,1181678,¿Quieres ser mi hijo?,Comedy|Romance,2023-09-21,¿Quieres ser mi hijo?,English,2.1586,8.576,284,False
3,240,The Godfather Part II,Drama|Crime,1974-12-20,The Godfather Part II,English,15.2780,8.571,12923,False
4,424,Schindler's List,Drama|History|War,1993-12-15,Schindler's List,English,40.5468,8.565,16396,False
...,...,...,...,...,...,...,...,...,...,...
9995,58013,The Santa Claus Gang,Comedy,2010-12-17,La banda dei Babbi Natale,Italian,0.9498,6.026,1054,False
9996,27526,The Crossing Guard,Drama|Thriller,1995-01-26,The Crossing Guard,English,4.9305,6.000,266,False
9997,13654,101 Dalmatians II: Patch's London Adventure,Family|Animation|Adventure|Comedy,2003-03-02,101 Dalmatians II: Patch's London Adventure,English,2.9521,6.026,1188,False
9998,9416,Money Talks,Comedy|Action|Crime,1997-08-22,Money Talks,English,7.2760,6.026,392,False
9999,8884,Franklyn,Fantasy|Thriller|Drama,2008-10-16,Franklyn,English,4.6225,6.000,360,False

In [57]:
# striping the spaces anyhow if it's in the data
for x in data.columns:
    if data[x].dtype == object:
        data[x] = data[x].str.strip()

# Database

### Injesting data to database

In [58]:
from sqlalchemy import create_engine

In [59]:
url = 'mysql+mysqlconnector://root:Ketan@localhost:3306/API_data'
engine = create_engine(url)

In [60]:
data.to_sql('tmdb_api_cleaned_data',con = engine, index = False , if_exists = 'replace')

10000